=== gaddalecharmi/CSEA-23071A0516/bookstore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="bookstore">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="lang" type="xs:string" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
              <xs:element name="author" type="xs:string"/>
              <xs:element name="year" type="xs:gYear"/>
              <xs:element name="price" type="xs:decimal"/>
            </xs:sequence>
            <xs:attribute name="category" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== gaddalecharmi/CSEA-23071A0516/bookstore-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<bookstore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="bookstore.xsd">
    <book category="Fiction">
        <title lang="en">To Kill a Mockingbird</title>
        <author>Harper Lee</author>
        <year>1960</year>
        <price>10.99</price>
    </book>
    <book category="Science Fiction">
        <title lang="en">Dune</title>
        <author>Frank Herbert</author>
        <year>1965</year>
        <price>15.99</price>
    </book>
    <book category="Fantasy">
        <title lang="en">The Hobbit</title>
        <author>J.R.R. Tolkien</author>
        <price>12.99</price>
        <year>1937</year>
    </book>
</bookstore>
